[package]
name = "egui-log-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = { version = "0.27.2" }
eframe = { version = "0.27.2" }
rfd = "0.14.1"
futures = "0.3.30"